<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1672996223138</name>
   <tag></tag>
   <elementGuidId>9277d8e8-4148-4858-a400-dcd4db925dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>61018271-e1da-44c4-9c61-a96a3e8a98a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1672996223138</value>
      <webElementGuid>9eec730c-e412-44d9-b732-31aca1bd1f82</webElementGuid>
   </webElementProperties>
</WebElementEntity>
