<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1672996243353</name>
   <tag></tag>
   <elementGuidId>d7e60da9-39c6-4679-bad3-e37bdae7a9d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3d18b61a-d18b-4f30-a032-7e1073ffc57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1672996243353</value>
      <webElementGuid>ce3882e5-8bbd-4b61-a2a7-6b337136d908</webElementGuid>
   </webElementProperties>
</WebElementEntity>
